/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'pv',
    path: '/pv',
    component: 'layout.base',
    meta: {
      title: '光伏监控',
      i18nKey: 'route.pv',
      icon: 'mdi:solar-power-variant',
      order: 2
    },
    children: [
      {
        name: 'pv_3d-model',
        path: '/pv/3d-model',
        component: 'view.pv_3d-model',
        meta: {
          title: '3D模型查看',
          i18nKey: 'route.pv_3d-model',
          keepAlive: true,
          order: 3
        }
      },
      {
        name: 'pv_panel-detail',
        path: '/pv/panel-detail',
        component: 'view.pv_panel-detail',
        props: true,
        meta: {
          title: '单板数据分析',
          i18nKey: 'route.pv_panel-detail',
          hideInMenu: true,
          keepAlive: true
        }
      },
      {
        name: 'pv_system',
        path: '/pv/system',
        component: 'view.pv_system',
        meta: {
          title: '光伏板状态',
          i18nKey: 'route.pv_system',
          keepAlive: true,
          order: 2
        }
      }
    ]
  }
];
